// All users Auth
export const userAuth = {
  // DOCTOR Auth
  DOCTOR_SIGN_UP_REQUEST: "DOCTOR_SIGN_UP_REQUEST",
  DOCTOR_SIGN_UP_SUCCESS: "DOCTOR_SIGN_UP_SUCCESS",
  DOCTOR_SIGN_UP_FAIL: "DOCTOR_SIGN_UP_FAIL",
  DOCTOR_LOGIN_REQUEST: "DOCTOR_LOGIN_REQUEST",
  DOCTOR_LOGIN_SUCCESS: "DOCTOR_LOGIN_SUCCESS",
  DOCTOR_LOGIN_FAIL: "DOCTOR_LOGIN_FAIL",
  DOCTOR_LOGOUT_SUCCESS: "DOCTOR_LOGOUT_SUCCESS",
  DOCTOR_LOGOUT_REQUEST: "DOCTOR_LOGOUT_REQUEST",

  // USER Auth
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_FAIL: "USER_SIGN_UP_FAIL",
  USER_SIGN_UP_REQUEST: "USER_SIGN_UP_REQUEST",
  USER_LOG_IN_SUCCESS: "USER_LOG_IN_SUCCESS",
  USER_LOG_IN_FAIL: "USER_LOG_IN_FAIL",
  USER_LOG_IN_REQUEST: "USER_LOG_IN_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",

  // Admin Auth
  ADMIN_REGISTRATION_SUCCESS: "ADMIN_REGISTRATION_SUCCESS",
  ADMIN_REGISTRATION_FAIL: "ADMIN_REGISTRATION_FAIL",
  ADMIN_REGISTRATION_REQUEST: "ADMIN_REGISTRATION_REQUEST",
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
  ADMIN_LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
  ADMIN_LOGOUT_REQUEST: "ADMIN_LOGOUT_REQUEST",
};

export const LOGIN_LOADING_SUCCESS = "LOGIN_LOADING_SUCCESS";
export const GET_ORDERS_LOADER = "GET_ORDERS_LOADER";
export const GET_GIGS_LOADER = "GET_GIGS_LOADER";
export const GET_REPORTS_LOADER = "GET_REPORTS_LOADER";
export const GET_NOTIFICATIONS_LOADER = "GET_NOTIFICATIONS_LOADER";
export const GET_BLOGS_LOADER = "GET_BLOGS_LOADER";

// USERs Types
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";

export const DELETE_USER_ACCOUNT_SUCCESS =
  "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL";
export const DELETE_USER_ACCOUNT_REQUEST =
  "DELETE_USER_ACCOUNT_REQUEST";

export const FORGET_USER_PASSWORD_SUCCESS =
  "FORGET_USER_PASSWORD_SUCCESS";
export const FORGET_USER_PASSWORD_FAIL =
  "FORGET_USER_PASSWORD_FAIL";
export const FORGET_USER_PASSWORD_REQUEST =
  "FORGET_USER_PASSWORD_REQUEST";

export const VERIFY_USER_TOKEN_SUCCESS =
  "VERIFY_USER_TOKEN_SUCCESS";
export const VERIFY_USER_TOKEN_FAIL = "VERIFY_USER_TOKEN_FAIL";
export const VERIFY_USER_TOKEN_REQUEST =
  "VERIFY_USER_TOKEN_REQUEST";

export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAIL = "SEND_OTP_FAIL";
export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";
export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";

export const RESET_USER_PASSWORD_SUCCESS =
  "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAIL = "RESET_USER_PASSWORD_FAIL";
export const RESET_USER_PASSWORD_REQUEST =
  "RESET_USER_PASSWORD_REQUEST";

export const ADD_USER_PAYMENT_SUCCESS = "ADD_USER_PAYMENT_SUCCESS";
export const ADD_USER_PAYMENT_FAIL = "ADD_USER_PAYMENT_FAIL";
export const ADD_USER_PAYMENT_REQUEST = "ADD_USER_PAYMENT_REQUEST";

export const GET_USER_PAYMENT_FAIL = "GET_USER_PAYMENT_FAIL";
export const GET_USER_PAYMENT_SUCCESS = "GET_USER_PAYMENT_SUCCESS";
export const GET_USER_PAYMENT_REQUEST = "GET_USER_PAYMENT_REQUEST";

export const DELETE_USER_PAYMENT_SUCCESS =
  "DELETE_USER_PAYMENT_SUCCESS";
export const DELETE_USER_PAYMENT_FAIL = "DELETE_USER_PAYMENT_FAIL";
export const DELETE_USER_PAYMENT_REQUEST =
  "DELETE_USER_PAYMENT_REQUEST";

export const ADD_PET_PROFILES_SUCCESS = "ADD_PET_PROFILES_SUCCESS";
export const ADD_PET_PROFILES_FAIL = "ADD_PET_PROFILES_FAIL";
export const ADD_PET_PROFILES_REQUEST = "ADD_PET_PROFILES_REQUEST";

export const GET_ALL_USER_PET_PROFILES_SUCCESS =
  "GET_ALL_USER_PET_PROFILES_SUCCESS";
export const GET_ALL_USER_PET_PROFILES_FAIL =
  "GET_ALL_USER_PET_PROFILES_FAIL";
export const GET_ALL_USER_PET_PROFILES_REQUEST =
  "GET_ALL_USER_PET_PROFILES_REQUEST";

export const GET_ALL_MY_PET_PROFILES_SUCCESS =
  "GET_ALL_MY_PET_PROFILES_SUCCESS";
export const GET_ALL_MY_PET_PROFILES_FAIL =
  "GET_ALL_MY_PET_PROFILES_FAIL";
export const GET_ALL_MY_PET_PROFILES_REQUEST =
  "GET_ALL_MY_PET_PROFILES_REQUEST";

export const UPDATE_PET_PROFILES_SUCCESS = "UPDATE_PET_PROFILES_SUCCESS";
export const UPDATE_PET_PROFILES_FAIL = "UPDATE_PET_PROFILES_FAIL";
export const UPDATE_PET_PROFILES_REQUEST = "UPDATE_PET_PROFILES_REQUEST";

export const CREATE_NEW_USER_CONVERSATION_SUCCESS =
  "CREATE_NEW_USER_CONVERSATION_SUCCESS";
export const CREATE_NEW_USER_CONVERSATION_FAIL =
  "CREATE_NEW_USER_CONVERSATION_FAIL";
export const CREATE_NEW_USER_CONVERSATION_REQUEST =
  "CREATE_NEW_USER_CONVERSATION_REQUEST";

export const GET_USER_MESSAGES_SUCCESS =
  "GET_USER_MESSAGES_SUCCESS";
export const GET_USER_MESSAGES_FAIL = "GET_USER_MESSAGES_FAIL";
export const GET_USER_MESSAGES_REQUEST =
  "GET_USER_MESSAGES_REQUEST";

export const USER_PET_PROFILE_PROPOSAL_SENT_SUCCESS =
  "USER_PET_PROFILE_PROPOSAL_SENT_SUCCESS";
export const USER_PET_PROFILE_PROPOSAL_SENT_FAIL =
  "USER_PET_PROFILE_PROPOSAL_SENT_FAIL";
export const USER_PET_PROFILE_PROPOSAL_SENT_REQUEST =
  "USER_PET_PROFILE_PROPOSAL_SENT_REQUEST";

export const USER_PET_PROFILE_PROPOSAL_UPDATE_SUCCESS =
  "USER_PET_PROFILE_PROPOSAL_UPDATE_SUCCESS";
export const USER_PET_PROFILE_PROPOSAL_UPDATE_FAIL =
  "USER_PET_PROFILE_PROPOSAL_UPDATE_FAIL";
export const USER_PET_PROFILE_PROPOSAL_UPDATE_REQUEST =
  "USER_PET_PROFILE_PROPOSAL_UPDATE_REQUEST";

export const DELETE_PET_PROFILE_REQUEST_SUCCESS =
  "DELETE_PET_PROFILE_REQUEST_SUCCESS";
export const DELETE_PET_PROFILE_REQUEST_FAIL =
  "DELETE_PET_PROFILE_REQUEST_FAIL";
export const DELETE_PET_PROFILE_REQUEST_REQUEST =
  "DELETE_PET_PROFILE_REQUEST_REQUEST";

export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";
export const ACCEPT_REQUEST_REQUEST = "ACCEPT_REQUEST_REQUEST";

export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const REJECT_REQUEST_FAIL = "REJECT_REQUEST_FAIL";
export const REJECT_REQUEST_REQUEST = "REJECT_REQUEST_REQUEST";

export const GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_SUCCESS =
  "GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_SUCCESS";
export const GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_FAIL =
  "GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_FAIL";
export const GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_REQUEST =
  "GET_ALL_SUBMITTED_PET_PROFILES_REQUESTS_REQUEST";

export const GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_SUCCESS =
  "GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_SUCCESS";
export const GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_FAIL =
  "GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_FAIL";
export const GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_REQUEST =
  "GET_ALL_RECEIVED_PET_PROFILES_REQUESTS_REQUEST";

export const DELETE_PET_PROFILES_SUCCESS = "DELETE_PET_PROFILES_SUCCESS";
export const DELETE_PET_PROFILES_FAIL = "DELETE_PET_PROFILES_FAIL";
export const DELETE_PET_PROFILES_REQUEST = "DELETE_PET_PROFILES_REQUEST";

export const GET_ALL_USER_JOBS_SUCCESS =
  "GET_ALL_USER_JOBS_SUCCESS";
export const GET_ALL_USER_JOBS_FAIL = "GET_ALL_USER_JOBS_FAIL";
export const GET_ALL_USER_JOBS_REQUEST =
  "GET_ALL_USER_JOBS_REQUEST";

export const COMPLETE_USER_PROFILE_SUCCESS =
  "COMPLETE_USER_PROFILE_SUCCESS";
export const COMPLETE_USER_PROFILE_FAIL =
  "COMPLETE_USER_PROFILE_FAIL";
export const COMPLETE_USER_PROFILE_REQUEST =
  "COMPLETE_USER_PROFILE_REQUEST";

export const UPDATE_USER_ACCOUNT_SUCCESS =
  "UPDATE_USER_ACCOUNT_SUCCESS";
export const UPDATE_USER_ACCOUNT_FAIL = "UPDATE_USER_ACCOUNT_FAIL";
export const UPDATE_USER_ACCOUNT_REQUEST =
  "UPDATE_USER_ACCOUNT_REQUEST";

export const CREATE_NEW_BLOG_REPLY_COMMENT_USER_SUCCESS =
  "CREATE_NEW_BLOG_REPLY_COMMENT_USER_SUCCESS";

export const CREATE_NEW_BLOG_REPLY_COMMENT_USER_FAIL =
  "CREATE_NEW_BLOG_REPLY_COMMENT_USER_FAIL";

export const CREATE_NEW_BLOG_REPLY_COMMENT_USER_REQUEST =
  "CREATE_NEW_BLOG_REPLY_COMMENT_USER_REQUEST";

export const GET_USER_REVIEWS_SUCCESS = "GET_USER_REVIEWS_SUCCESS";
export const GET_USER_REVIEWS_FAIL = "GET_USER_REVIEWS_FAIL";
export const GET_USER_REVIEWS_REQUEST = "GET_USER_REVIEWS_REQUEST";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";

export const GET_ALL_USER_ORDERS_SUCCESS =
  "GET_ALL_USER_ORDERS_SUCCESS";
export const GET_ALL_USER_ORDERS_FAIL = "GET_ALL_USER_ORDERS_FAIL";
export const GET_ALL_USER_ORDERS_REQUEST =
  "GET_ALL_USER_ORDERS_REQUEST";

export const READ_USER_NOTIFICATION_SUCCESS =
  "READ_USER_NOTIFICATION_SUCCESS";
export const READ_USER_NOTIFICATION_FAIL =
  "READ_USER_NOTIFICATION_FAIL";
export const READ_USER_NOTIFICATION_REQUEST =
  "READ_USER_NOTIFICATION_REQUEST";

export const GET_MY_USER_BLOGS_SUCCESS = "GET_MY_USER_BLOGS_FAIL";
export const GET_MY_USER_BLOGS_FAIL = "GET_MY_USER_BLOGS_FAIL";
export const GET_MY_USER_BLOGS_REQUEST =
  "GET_MY_USER_BLOGS_REQUEST";

export const GET_ALL_USER_PET_PROFILES_ORDERS_SUCCESS =
  "GET_ALL_USER_PET_PROFILES_ORDERS_SUCCESS";
export const GET_ALL_USER_PET_PROFILES_ORDERS_FAIL =
  "GET_ALL_USER_PET_PROFILES_ORDERS_FAIL";
export const GET_ALL_USER_PET_PROFILES_ORDERS_REQUEST =
  "GET_ALL_USER_PET_PROFILES_ORDERS_REQUEST";

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";

export const CREATE_NEW_BLOG_COMMENT_SUCCESS =
  "CREATE_NEW_BLOG_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_COMMENT_FAIL = "CREATE_NEW_BLOG_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_COMMENT_REQUEST =
  "CREATE_NEW_BLOG_COMMENT_REQUEST";

export const CREATE_NEW_BLOG_REPLY_COMMENT_SUCCESS =
  "CREATE_NEW_BLOG_REPLY_COMMENT_SUCCESS";
export const CREATE_NEW_BLOG_REPLY_COMMENT_FAIL =
  "CREATE_NEW_BLOG_REPLY_COMMENT_FAIL";
export const CREATE_NEW_BLOG_REPLY_COMMENT_REQUEST =
  "CREATE_NEW_BLOG_REPLY_COMMENT_REQUEST";

export const GET_ALL_USER_BLOGS_SUCCESS =
  "GET_ALL_USER_BLOGS_SUCCESS";
export const GET_ALL_USER_BLOGS_FAIL = "GET_ALL_USER_BLOGS_FAIL";
export const GET_ALL_USER_BLOGS_REQUEST =
  "GET_ALL_USER_BLOGS_REQUEST";

export const GET_USER_ALL_REVIEWS_SUCCESS =
  "GET_USER_ALL_REVIEWS_SUCCESS";

export const GET_USER_ALL_REVIEWS_FAIL =
  "GET_USER_ALL_REVIEWS_FAIL";

export const GET_USER_ALL_REVIEWS_REQUEST =
  "GET_USER_ALL_REVIEWS_REQUEST";

export const GET_ALL_USER_REPORTS_SUCCESS =
  "GET_ALL_USER_REPORTS_SUCCESS";
export const GET_ALL_USER_REPORTS_FAIL =
  "GET_ALL_USER_REPORTS_FAIL";
export const GET_ALL_USER_REPORTS_REQUEST =
  "GET_ALL_USER_REPORTS_REQUEST";
// Proposal
export const USER_PROPOSAL_SENT_SUCCESS =
  "USER_PROPOSAL_SENT_SUCCESS";
export const USER_PROPOSAL_SENT_FAIL = "USER_PROPOSAL_SENT_FAIL";
export const USER_PROPOSAL_SENT_REQUEST =
  "USER_PROPOSAL_SENT_REQUEST";

export const CREATE_NEW_BLOG_SUCCESS = "CREATE_NEW_BLOG_SUCCESS";
export const CREATE_NEW_BLOG_FAIL = "CREATE_NEW_BLOG_FAIL";
export const CREATE_NEW_BLOG_REQUEST = "CREATE_NEW_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
// Admin
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_DOCTORS_SUCCESS = "GET_ALL_DOCTORS_SUCCESS";
export const GET_ALL_DOCTORS_FAIL = "GET_ALL_DOCTORS_FAIL";
export const GET_ALL_DOCTORS_REQUEST = "GET_ALL_DOCTORS_REQUEST";
export const GET_ALL_ADMIN_PET_PROFILES_SUCCESS =
  "GET_ALL_ADMIN_PET_PROFILES_SUCCESS";
export const GET_ALL_ADMIN_PET_PROFILES_FAIL =
  "GET_ALL_ADMIN_PET_PROFILES_FAIL";
export const GET_ALL_ADMIN_PET_PROFILES_REQUEST =
  "GET_ALL_ADMIN_PET_PROFILES_REQUEST";
export const GET_ADMIN_JOB_PROPOSALS_SUCCESS =
  "GET_ADMIN_JOB_PROPOSALS_SUCCESS";
export const GET_ADMIN_PET_PROFILES_REQUESTS_SUCCESS =
  "GET_ADMIN_PET_PROFILES_REQUESTS_SUCCESS";
export const GET_ADMIN_PET_PROFILES_REQUESTS_FAIL =
  "GET_ADMIN_PET_PROFILES_REQUESTS_FAIL";
export const GET_ADMIN_PET_PROFILES_REQUESTS_REQUEST =
  "GET_ADMIN_PET_PROFILES_REQUESTS_REQUEST";
export const GET_ADMIN_JOB_PROPOSALS_FAIL = "GET_ADMIN_JOB_PROPOSALS_FAIL";
export const GET_ADMIN_JOB_PROPOSALS_REQUEST =
  "GET_ADMIN_JOB_PROPOSALS_REQUEST";
export const GET_ADMIN_BLOGS_SUCCESS = "GET_ADMIN_BLOGS_SUCCESS";
export const GET_ADMIN_BLOGS_FAIL = "GET_ADMIN_BLOGS_FAIL";
export const GET_ADMIN_BLOGS_REQUEST = "GET_ADMIN_BLOGS_REQUEST";
export const GET_ADMIN_ALL_GIGS_SUCCESS = "GET_ADMIN_ALL_GIGS_SUCCESS";
export const GET_ADMIN_ALL_GIGS_FAIL = "GET_ADMIN_ALL_GIGS_FAIL";
export const GET_ADMIN_ALL_GIGS_REQUEST = "GET_ADMIN_ALL_GIGS_REQUEST";
export const GET_ADMIN_JOBS_SUCCESS = "GET_ADMIN_JOBS_SUCCESS";
export const GET_ADMIN_JOBS_FAIL = "GET_ADMIN_JOBS_FAIL";
export const GET_ADMIN_JOBS_REQUEST = "GET_ADMIN_JOBS_REQUEST";
export const GET_ADMIN_ORDERS_SUCCESS = "GET_ADMIN_ORDERS_SUCCESS";
export const GET_ADMIN_ORDERS_FAIL = "GET_ADMIN_ORDERS_FAIL";
export const GET_ADMIN_ORDERS_REQUEST = "GET_ADMIN_ORDERS_REQUEST";
export const GET_ADMIN_USER_REVIEWS_SUCCESS =
  "GET_ADMIN_USER_REVIEWS_SUCCESS";
export const GET_ADMIN_USER_REVIEWS_FAIL =
  "GET_ADMIN_USER_REVIEWS_FAIL";
export const GET_ADMIN_USER_REVIEWS_REQUEST =
  "GET_ADMIN_USER_REVIEWS_REQUEST";
export const GET_ADMIN_BLOGS_COMMENTS_SUCCESS =
  "GET_ADMIN_BLOGS_COMMENTS_SUCCESS";
export const GET_ADMIN_BLOGS_COMMENTS_FAIL =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const GET_ADMIN_BLOGS_COMMENTS_REQUEST =
  "GET_ADMIN_BLOGS_COMMENTS_REQUEST";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const GET_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST =
  "GET_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";
/* DELETE */

export const DELETE_ALL_USER_SUCCESS = "DELETE_ALL_USER_SUCCESS";
export const DELETE_ALL_USER_FAIL = "DELETE_ALL_USER_FAIL";
export const DELETE_ALL_USER_REQUEST = "DELETE_ALL_USER_REQUEST";
export const DELETE_ALL_DOCTORS_SUCCESS = "DELETE_ALL_DOCTORS_SUCCESS";
export const DELETE_ALL_DOCTORS_FAIL = "DELETE_ALL_DOCTORS_FAIL";
export const DELETE_ALL_DOCTORS_REQUEST = "DELETE_ALL_DOCTORS_REQUEST";
export const DELETE_ALL_ADMIN_PET_PROFILES_SUCCESS =
  "DELETE_ALL_ADMIN_PET_PROFILES_SUCCESS";
export const DELETE_ALL_ADMIN_PET_PROFILES_FAIL =
  "DELETE_ALL_ADMIN_PET_PROFILES_FAIL";
export const DELETE_ALL_ADMIN_PET_PROFILES_REQUEST =
  "DELETE_ALL_ADMIN_PET_PROFILES_REQUEST";
export const DELETE_ADMIN_JOB_PROPOSALS_SUCCESS =
  "DELETE_ADMIN_JOB_PROPOSALS_SUCCESS";
export const DELETE_ADMIN_JOB_PROPOSALS_FAIL =
  "DELETE_ADMIN_JOB_PROPOSALS_FAIL";
export const DELETE_ADMIN_JOB_PROPOSALS_REQUEST =
  "DELETE_ADMIN_JOB_PROPOSALS_REQUEST";
export const DELETE_ADMIN_PET_PROFILES_REQUESTS_SUCCESS =
  "DELETE_ADMIN_PET_PROFILES_REQUESTS_SUCCESS";
export const DELETE_ADMIN_PET_PROFILES_REQUESTS_FAIL =
  "DELETE_ADMIN_PET_PROFILES_REQUESTS_FAIL";
export const DELETE_ADMIN_PET_PROFILES_REQUESTS_REQUEST =
  "DELETE_ADMIN_PET_PROFILES_REQUESTS_REQUEST";

export const DELETE_ADMIN_BLOGS_SUCCESS = "DELETE_ADMIN_BLOGS_SUCCESS";
export const DELETE_ADMIN_BLOGS_FAIL = "DELETE_ADMIN_BLOGS_FAIL";
export const DELETE_ADMIN_BLOGS_REQUEST = "DELETE_ADMIN_BLOGS_REQUEST";
export const DELETE_ADMIN_ALL_GIGS_SUCCESS = "DELETE_ADMIN_ALL_GIGS_SUCCESS";
export const DELETE_ADMIN_ALL_GIGS_FAIL = "DELETE_ADMIN_ALL_GIGS_FAIL";
export const DELETE_ADMIN_ALL_GIGS_REQUEST = "DELETE_ADMIN_ALL_GIGS_REQUEST";
export const DELETE_ADMIN_JOBS_SUCCESS = "DELETE_ADMIN_JOBS_SUCCESS";
export const DELETE_ADMIN_JOBS_FAIL = "DELETE_ADMIN_JOBS_FAIL";
export const DELETE_ADMIN_JOBS_REQUEST = "DELETE_ADMIN_JOBS_REQUEST";
export const DELETE_ADMIN_ORDERS_SUCCESS = "DELETE_ADMIN_ORDERS_SUCCESS";
export const DELETE_ADMIN_ORDERS_FAIL = "DELETE_ADMIN_ORDERS_FAIL";
export const DELETE_ADMIN_ORDERS_REQUEST = "DELETE_ADMIN_ORDERS_REQUEST";
export const DELETE_ADMIN_USER_REVIEWS_SUCCESS =
  "DELETE_ADMIN_USER_REVIEWS_SUCCESS";
export const DELETE_ADMIN_USER_REVIEWS_FAIL =
  "DELETE_ADMIN_USER_REVIEWS_FAIL";
export const DELETE_ADMIN_USER_REVIEWS_REQUEST =
  "DELETE_ADMIN_USER_REVIEWS_REQUEST";
export const DELETE_ADMIN_BLOGS_COMMENTS_SUCCESS =
  "DELETE_ADMIN_BLOGS_COMMENTS_SUCCESS";
export const DELETE_ADMIN_BLOGS_COMMENTS_FAIL =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const DELETE_ADMIN_BLOGS_COMMENTS_REQUEST =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_SUCCESS";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_FAIL";
export const DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST =
  "DELETE_ADMIN_BLOGS_REPLY_COMMENTS_REQUEST";

export const GET_ADMIN_MESSAGES_SUCCESS = " GET_ADMIN_MESSAGES_SUCCESS";
export const GET_ADMIN_MESSAGES_FAIL = " GET_ADMIN_MESSAGES_FAIL";
export const GET_ADMIN_MESSAGES_REQUEST = " GET_ADMIN_MESSAGES_REQUEST";

// Gigs
export const CREATE_NEW_GIG_SUCCESS = "CREATE_NEW_GIG_SUCCESS";
export const CREATE_NEW_GIG_FAIL = "CREATE_NEW_GIG_FAIL";
export const CREATE_NEW_GIG_REQUEST = "CREATE_NEW_GIG_REQUEST";

export const EDIT_GIG_SUCCESS = "EDIT_GIG_SUCCESS";
export const EDIT_GIG_FAIL = "EDIT_GIG_FAIL";
export const EDIT_GIG_REQUEST = "EDIT_GIG_REQUEST";

export const DELETE_GIG_SUCCESS = "DELETE_GIG_SUCCESS";
export const DELETE_GIG_FAIL = "DELETE_GIG_FAIL";
export const DELETE_GIG_REQUEST = "DELETE_GIG_REQUEST";

export const GET_ALL_GIGS_SUCCESS = "GET_ALL_GIGS_SUCCESS";
export const GET_ALL_GIGS_FAIL = "GET_ALL_GIGS_FAIL";
export const GET_ALL_GIGS_REQUEST = "GET_ALL_GIGS_REQUEST";

export const ACCEPT_GIG_ORDER_SUCCESS = "ACCEPT_GIG_ORDER_SUCCESS";
export const ACCEPT_GIG_ORDER_FAIL = "ACCEPT_GIG_ORDER_FAIL";
export const ACCEPT_GIG_ORDER_REQUEST = "ACCEPT_GIG_ORDER_REQUEST";

export const CREATE_NEW_GIG_ORDER_SUCCESS = "CREATE_NEW_GIG_ORDER_SUCCESS";
export const CREATE_NEW_GIG_ORDER_FAIL = "CREATE_NEW_GIG_ORDER_FAIL";
export const CREATE_NEW_GIG_ORDER_REQUEST = "CREATE_NEW_GIG_ORDER_REQUEST";

export const GET_MY_GIGS_SUCCESS = "GET_ALL_GIGS_SUCCESS";
export const GET_MY_GIGS_FAIL = "GET_ALL_GIGS_FAIL";
export const GET_MY_GIGS_REQUEST = "GET_ALL_GIGS_REQUEST";

// Jobs
export const CREATE_NEW_JOB_SUCCESS = "CREATE_NEW_JOB_SUCCESS";
export const CREATE_NEW_JOB_FAIL = "CREATE_NEW_JOB_FAIL";
export const CREATE_NEW_JOB_REQUEST = "CREATE_NEW_JOB_REQUEST";

export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_FAIL = "EDIT_JOB_FAIL";
export const EDIT_JOB_REQUEST = "EDIT_JOB_REQUEST";

export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";

export const GET_ALL_JOBS_SUCCESS = "GET_ALL_JOBS_SUCCESS";
export const GET_ALL_JOBS_FAIL = "GET_ALL_JOBS_FAIL";
export const GET_ALL_JOBS_REQUEST = "GET_ALL_JOBS_REQUEST";

export const GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_SUCCESS =
  " GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_SUCCESS";
export const GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_FAIL =
  " GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_FAIL";
export const GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_REQUEST =
  " GET_ALL_JOBS_PROPOSALS_FOR_DOCTOR_REQUEST";

export const GET_USER_DOCTOR_REVIEWS_SUCCESS =
  " GET_USER_DOCTOR_REVIEWS_SUCCESS";

export const GET_USER_DOCTOR_REVIEWS_FAIL =
  " GET_USER_DOCTOR_REVIEWS_FAIL";

export const GET_USER_DOCTOR_REVIEWS_REQUEST =
  " GET_USER_DOCTOR_REVIEWS_REQUEST";

export const GET_ALL_JOBS_PROPOSALS_FOR_USER_SUCCESS =
  " GET_ALL_JOBS_PROPOSALS_FOR_USER_SUCCESS";
export const GET_ALL_JOBS_PROPOSALS_FOR_USER_FAIL =
  " GET_ALL_JOBS_PROPOSALS_FOR_USER_FAIL";
export const GET_ALL_JOBS_PROPOSALS_FOR_USER_REQUEST =
  " GET_ALL_JOBS_PROPOSALS_FOR_USER_REQUEST";

export const DELETE_JOB_PROPOSAL_SUCCESS = " DELETE_JOB_PROPOSAL_SUCCESS";
export const DELETE_JOB_PROPOSAL_FAIL = " DELETE_JOB_PROPOSAL_FAIL";
export const DELETE_JOB_PROPOSAL_REQUEST = " DELETE_JOB_PROPOSAL_REQUEST";

// Proposals

export const ACCEPT_PROPOSAL_SUCCESS = "ACCEPT_PROPOSAL_SUCCESS";
export const ACCEPT_PROPOSAL_FAIL = "ACCEPT_PROPOSAL_FAIL";
export const ACCEPT_PROPOSAL_REQUEST = "ACCEPT_PROPOSAL_REQUEST";

export const REJECT_PROPOSAL_SUCCESS = "REJECT_PROPOSAL_SUCCESS";
export const REJECT_PROPOSAL_FAIL = "REJECT_PROPOSAL_FAIL";
export const REJECT_PROPOSAL_REQUEST = "REJECT_PROPOSAL_REQUEST";

export const EDIT_PROPOSAL_SUCCESS = "EDIT_PROPOSAL_SUCCESS";
export const EDIT_PROPOSAL_FAIL = "EDIT_PROPOSAL_FAIL";
export const EDIT_PROPOSAL_REQUEST = "EDIT_PROPOSAL_REQUEST";

// DOCTORs
export const GET_DOCTOR_PROFILE_SUCCESS = "GET_DOCTOR_PROFILE_SUCCESS";
export const GET_DOCTOR_PROFILE_FAIL = "GET_DOCTOR_PROFILE_FAIL";
export const GET_DOCTOR_PROFILE_REQUEST = "GET_DOCTOR_PROFILE_REQUEST";

export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAIL = "ADD_PAYMENT_FAIL";
export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";

export const GET_PAYMENT_FAIL = "GET_PAYMENT_FAIL";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";

export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";
export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";

export const SUBMIT_REVIEW_SUCCESS = "SUBMIT_REVIEW_SUCCESS";
export const SUBMIT_REVIEW_FAIL = "SUBMIT_REVIEW_FAIL";
export const SUBMIT_REVIEW_REQUEST = "SUBMIT_REVIEW_REQUEST";

export const UPDATE_DOCTOR_PROFILE_SUCCESS = "UPDATE_DOCTOR_PROFILE_SUCCESS";
export const UPDATE_DOCTOR_PROFILE_FAIL = "UPDATE_DOCTOR_PROFILE_FAIL";
export const UPDATE_DOCTOR_PROFILE_REQUEST = "UPDATE_DOCTOR_PROFILE_REQUEST";

export const UPDATE_DOCTOR_ACCOUNT_SUCCESS = "UPDATE_DOCTOR_ACCOUNT_SUCCESS";
export const UPDATE_DOCTOR_ACCOUNT_FAIL = "UPDATE_DOCTOR_ACCOUNT_FAIL";
export const UPDATE_DOCTOR_ACCOUNT_REQUEST = "UPDATE_DOCTOR_ACCOUNT_REQUEST";

export const RESET_DOCTOR_PASSWORD_SUCCESS = "RESET_DOCTOR_PASSWORD_SUCCESS";
export const RESET_DOCTOR_PASSWORD_FAIL = "RESET_DOCTOR_PASSWORD_FAIL";
export const RESET_DOCTOR_PASSWORD_REQUEST = "RESET_DOCTOR_PASSWORD_REQUEST";

export const VERIFY_DOCTOR_TOKEN_SUCCESS = "VERIFY_DOCTOR_TOKEN_SUCCESS";
export const VERIFY_DOCTOR_TOKEN_FAIL = "VERIFY_DOCTOR_TOKEN_FAIL";
export const VERIFY_DOCTOR_TOKEN_REQUEST = "VERIFY_DOCTOR_TOKEN_REQUEST";

export const CREATE_NEW_DOCTOR_CONVERSATION_SUCCESS =
  "CREATE_NEW_DOCTOR_CONVERSATION_SUCCESS";
export const CREATE_NEW_DOCTOR_CONVERSATION_FAIL =
  "CREATE_NEW_DOCTOR_CONVERSATION_FAIL";
export const CREATE_NEW_DOCTOR_CONVERSATION_REQUEST =
  "CREATE_NEW_DOCTOR_CONVERSATION_REQUEST";

export const GET_DOCTOR_MESSAGES_SUCCESS = "GET_DOCTOR_MESSAGES_SUCCESS";
export const GET_DOCTOR_MESSAGES_FAIL = "GET_DOCTOR_MESSAGES_FAIL";
export const GET_DOCTOR_MESSAGES_REQUEST = "GET_DOCTOR_MESSAGES_REQUEST";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

export const FORGET_DOCTOR_PASSWORD_SUCCESS = "FORGET_DOCTOR_PASSWORD_SUCCESS";
export const FORGET_DOCTOR_PASSWORD_FAIL = "FORGET_DOCTOR_PASSWORD_FAIL";
export const FORGET_DOCTOR_PASSWORD_REQUEST = "FORGET_DOCTOR_PASSWORD_REQUEST";

export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATION_FAIL";

export const GET_ALL_DOCTOR_REPORTS_SUCCESS = "GET_ALL_DOCTOR_REPORTS_SUCCESS";
export const GET_ALL_DOCTOR_REPORTS_FAIL = "GET_ALL_DOCTOR_REPORTS_FAIL";
export const GET_ALL_DOCTOR_REPORTS_REQUEST = "GET_ALL_DOCTOR_REPORTS_REQUEST";

export const DELETE_DOCTOR_ACCOUNT_SUCCESS = "DELETE_DOCTOR_ACCOUNT_SUCCESS";
export const DELETE_DOCTOR_ACCOUNT_FAIL = "DELETE_DOCTOR_ACCOUNT_FAIL";
export const DELETE_DOCTOR_ACCOUNT_REQUEST = "DELETE_DOCTOR_ACCOUNT_REQUEST";

export const GET_ALL_DOCTOR_BLOGS_SUCCESS = "GET_ALL_DOCTOR_BLOGS_SUCCESS";
export const GET_ALL_DOCTOR_BLOGS_FAIL = "GET_ALL_DOCTOR_BLOGS_FAIL";
export const GET_ALL_DOCTOR_BLOGS_REQUEST = "GET_ALL_DOCTOR_BLOGS_REQUEST";

export const SEND_OTP_DOCTOR_SUCCESS = "Send_OTP_DOCTOR_SUCCESS";
export const SEND_OTP_DOCTOR_FAIL = "Send_OTP_DOCTOR_FAIL";
export const SEND_OTP_DOCTOR_REQUEST = "Send_OTP_DOCTOR_REQUEST";

export const VERIFY_DOCTOR_EMAIL_SUCCESS = "VERIFY_DOCTOR_EMAIL_SUCCESS";
export const VERIFY_DOCTOR_EMAIL_FAIL = "VERIFY_DOCTOR_EMAIL_FAIL";
export const VERIFY_DOCTOR_EMAIL_REQUEST = "VERIFY_DOCTOR_EMAIL_REQUEST";

export const READ_DOCTOR_NOTIFICATION_SUCCESS =
  " READ_DOCTOR_NOTIFICATION_SUCCESS";
export const READ_DOCTOR_NOTIFICATION_FAIL = " READ_DOCTOR_NOTIFICATION_FAIL";
export const READ_DOCTOR_NOTIFICATION_REQUEST =
  " READ_DOCTOR_NOTIFICATION_REQUEST";

// Notifications
export const READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS";
export const READ_NOTIFICATION_FAIL = "READ_NOTIFICATION_FAIL";

// Blogs
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAIL = "GET_ALL_BLOGS_FAIL";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const REPLY_COMMENT_SUCCESS = "REPLY_COMMENT_SUCCESS";
export const REPLY_COMMENT_FAIL = "REPLY_COMMENT_FAIL";

// General
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";

// Guest

export const GET_ALL_GUEST_JOBS_SUCCESS = "GET_ALL_GUEST_JOBS_SUCCESS";
export const GET_ALL_GUEST_JOBS_FAIL = "GET_ALL_GUEST_JOBS_FAIL";
export const GET_ALL_GUEST_JOBS_REQUEST = "GET_ALL_GUEST_JOBS_REQUEST";

export const GET_ALL_GUEST_PET_PROFILES_SUCCESS =
  "GET_ALL_GUEST_PET_PROFILES_SUCCESS";
export const GET_ALL_GUEST_PET_PROFILES_FAIL =
  "GET_ALL_GUEST_PET_PROFILES_FAIL";
export const GET_ALL_GUEST_PET_PROFILES_REQUEST =
  "GET_ALL_GUEST_PET_PROFILES_REQUEST";

export const GET_ALL_GUEST_USERS_SUCCESS =
  " GET_ALL_GUEST_USERS_SUCCESS";
export const GET_ALL_GUEST_USERS_FAIL = " GET_ALL_GUEST_USERS_FAIL";
export const GET_ALL_GUEST_USERS_REQUEST =
  " GET_ALL_GUEST_USERS_REQUEST";

export const GET_GUEST_REVIEWS_SUCCESS = " GET_GUEST_REVIEWS_SUCCESS";
export const GET_GUEST_REVIEWS_FAIL = "GET_GUEST_REVIEWS_FAIL";
export const GET_GUEST_REVIEWS_REQUEST = "GET_GUEST_REVIEWS_REQUEST";
